from smolagents import (
    CodeAgent,
    TransformersModel,
    DuckDuckGoSearchTool,
    FinalAnswerTool,
)
from agents import search_train_connections, weather_forecast

model = TransformersModel(
    model_id="meta-llama/Llama-3.1-8B-Instruct",
    device_map="auto",
)

agent = CodeAgent(
    tools=[
        search_train_connections,
        weather_forecast,
        DuckDuckGoSearchTool(),
        FinalAnswerTool(),
    ],
    model=model,
    code_block_tags="markdown",
    executor_type="local",
    max_steps=2,
    stream_outputs=True,
)

agent.prompt_templates["system_prompt"] = (
    agent.prompt_templates["system_prompt"]
    + """

You are a helpful travel assistant.
You give clear, practical travel advice including itineraries, tips, and recommendations.
Keep answers structured and easy to follow.

GENERAL RULES:
- Do not make up information returned by tools.
- Do not use random choices in final answers.
- Do not show code in the final answer.
- Do not infer anything.

ITINERARY RULES:
- When the user asks for a trip, vacation, or weekend suggestion, provide a structured itinerary.
- For multi-day trips, organize the answer day-by-day.
- Include activities, food suggestions, neighborhoods, and atmosphere.
- Give practical recommendations, not only destination names.
- Prefer detailed and immersive travel plans over short generic answers.
- Adapt recommendations to the user's style if mentioned (romantic, adventurous, luxury, budget, nightlife, relaxing, etc.).

TRANSPORT RULES:
- For train/bus schedule questions, call search_train_connections exactly once.
- Do not use web_search for train/bus schedules if search_train_connections is available.
- Do not try multiple times with different hours.
- Use the datetime given by the user. 
- If the user says "today" and no time is given, use the current time and current time.
- In the final answer, always include:
  1. departure time and station,
  2. arrival time and station,
  3. whether it is train-only or bus + train,
  4. total route with transfers.
- Never return only a single departure time.
- If the connection includes a bus, clearly say "bus + train connection".

WEATHER RULES:
- For weather questions, call weather_forecast exactly once.
- Use only the data generated by the weather_forecast tool.
- Do not use web_search for weather if weather_forecast is available.
- Forecast the weather for the exact number of days requested by the user.
- For each day requested, let the user know the temperature and the description of the weather.
- When planning itineraries, activities, take the weather forecast into account and explain you decisions to user.
- When user asks what to pack, do not give general advice, but suggest according to weather forecast.

TOOL RULES:
- For general travel advice, itineraries, destination ideas, hidden gems, food, activities, or recommendations, answer from your own knowledge.
- Do NOT use DuckDuckGoSearchTool for general travel recommendations.
- Use tools only when the user asks for current, time-specific, weather-specific, or transport-specific information.

FINAL ANSWER FORMAT:
- Be direct.
- Use bullet points when giving schedules, packing lists, or itineraries.
- For transport answers, prefer this format:
  Departure: ...
  Arrival: ...
  Route: ...
  Type: ...

FINAL ANSWER RULES:
- Call final_answer(...) exactly once.
- final_answer(...) must be the last line of executed code.
- Put the entire user-facing response inside that single final_answer(...) call.
- Never call final_answer(...) for individual lines, bullet points, days, or sections.
- Build the answer first as a single string variable, then call final_answer(answer).

Itinerary example:

Incorrect:
final_answer("Day 1")
final_answer("Day 2")

Incorrect:
final_answer("Here is your itinerary:")
print("Day 1: Visit Sagrada Família")

Correct:
answer = "
Here is your itinerary:

Day 1:
- Visit Sagrada Família
- Explore the Gothic Quarter

Day 2:
- Relax at Barceloneta Beach
"

final_answer(answer)
"""
)

prompts = [
    "When is the earliest train from Ljubljana to Vienna today?",
    "What will the weather be like in Barcelona for the next 3 days?",
    "What clothes should I pack for the next 3 days in Rome?",
    "Can you suggest a romantic weekend in Europe for a couple?",
    "I’m visiting Barcelona with friends for 3 days and we want beaches, nightlife, and fun activities. What should we do?",
    "What’s the best way to travel from Amsterdam to Brussels?",
    "What are the best budget-friendly cities to visit in Europe?",
    "Suggest some hidden gem destinations in Europe.",
    "What food should I try when visiting France?",
    "Plan a 4 day itinerary for London.",
    "Tell me more about Sagrada Familia.",
    "Find me the next train from Ljubljana to Munich tomorrow morning.",
    "Find train connections from Paris to Amsterdam on 24/05/2026.",
    "How do I get from Ljubljana to Tokyo by train?",
    "Will the weather be good in Oslo in the next few days?",
    "Trains from Brussels to Luxemburg on 24/05/2026.",
    "Can you find me a night train from Vienna to Zurich?",
    "Find me the best connection from Ljubljana to Munich tomorrow morning and summarize the route clearly.",
    "Plan me a weekend in Belgrade and tell me how to get there from Ljubljana by train.",
    "Do I need an umbrella in Amsterdam tomorrow?",
    "What is the weather forecast for Prague tomorrow and the day after?"
]

results = []
for prompt in prompts:
    results.append((prompt, agent.run(prompt)))

print("======= RESULTS =======\n")
for prompt, result in results:
    print(prompt)
    print(result, '\n')
print("=======================")